---
- name: Launch EC2 Instance
  hosts: localhost
  connection: local
  # You can override this via --extra-vars
  tasks:
    - name: Start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        key_name: "iam"
        # vpc_subnet_id: subnet-013744e41e8088axx
        instance_type: "t2.micro"
        security_group: default
        region: us-west-1
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        network:
          assign_public_ip: true
        image_id: "{{ item.image }}"
        tags:
          Environment: Testing
      loop:
        - {image: "ami-0cbad6815f3a09a6d", name: "ansiblenode1"}
        - {image: "ami-014e30c8a36252ae5", name: "ansiblenode2"}
        - {image: "ami-014e30c8a36252ae5", name: "ansiblenode3"}