---
- hosts: all
  become: true
  tasks :
    # - name: getting the gathered ansible_facts
    #   ansible.builtin.debug:
    #     var: ansible_facts
    - name: shutting down the ubuntuuser
      ansible.builtin.command: /sbin/shutdown -t now
      when: ansible_facts['os_family'] == 'RedHat'

        